# Generated by Django 4.1.7 on 2023-02-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('version', models.IntegerField()),
                ('publisher_email', models.EmailField(max_length=254)),
                ('privacy', models.CharField(choices=[(1, 'Public'), (2, 'Private')], max_length=2)),
            ],
        ),
    ]
