# Generated by Django 4.1.7 on 2023-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publisher_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
