from django.db import models
from django.shortcuts import reverse, get_object_or_404
from categories.models import Category
# Create your models here.

## Model class represent table in the database
class Post(models.Model):
    # all fields generated by model ---> default not null,
    title = models.CharField(max_length=100)
    description  = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='posts/images', null=True, blank=True)
    version = models.IntegerField(default=1)
    publisher_email= models.EmailField(null=True,  blank=True)
    privacy = models.CharField(max_length=2, choices=[('1', 'Public'),('2', 'Private')])
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, null=True)
    # relation one to many ---> foreign key


    def __str__(self):
        return self.title

    def get_image_url(self):
        return f"/media/{self.image}"


    def get_show_url(self):
        return reverse('posts.show', args={self.id})

    def get_delete_url(self):
        print(reverse('posts.delete', args={self.id}) )
        return reverse('posts.delete', args={self.id})


    @classmethod
    def get_all_posts(cls):
        return cls.objects.all()


    @classmethod
    def get_spefic_post(cls, id):
        return get_object_or_404(cls, pk=id)
